version: '3'

services:
  mongo:
    image: mongo:3.7.3-jessie
    volumes:
      - /var/mongodb_data:/data/db
    ports:
      - 27017:27017

  backend:
    build: './backend'
    volumes:
      - /var/storage:/backend/storage
    ports:
      - 8080:8080
    depends_on: 
      - mongo


  frontend:
    build: './frontend/itec_frontend'
    ports:
      - 80:5000
    depends_on:
      - backend