version: '3'

services:
  mongo:
    image: mongo:3.7.3-jessie
    volumes:
      - /var/mongodb_data:/data/db


  backend:
    build: './backend'
    volumes:
      - /var/storage:/backend/storage
    ports:
      - 8080:8080
    depends_on: 
      - mongo


  frontend:
    build: './frontend/itec_frontend'
    ports:
      - 5000:5000
    depends_on:
      - backend


  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/archive/quizzard.club:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend